# Generated by Django 4.2.26 on 2025-11-07 09:14

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_contact_email_group_contact_person_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('loan_type', models.CharField(choices=[('short_term', 'Short Term Loan (3 months)'), ('long_term', 'Long Term Loan (2 years)'), ('project', 'Project Loan'), ('top_up', 'Top-Up Loan')], max_length=20)),
                ('principal_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Principal Amount')),
                ('interest_rate', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, verbose_name='Interest Rate (%)')),
                ('total_repayable', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Total Repayable')),
                ('application_date', models.DateField(auto_now_add=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('disbursement_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('short_term_months', models.PositiveIntegerField(default=3, verbose_name='Loan Period (months)')),
                ('long_term_months', models.PositiveIntegerField(default=24, verbose_name='Loan Period (months)')),
                ('project_description', models.TextField(blank=True, null=True, verbose_name='Project Description')),
                ('project_product', models.CharField(blank=True, max_length=255, null=True, verbose_name='Project Product')),
                ('id_verified', models.BooleanField(default=False, verbose_name='ID Verified')),
                ('id_verification_method', models.CharField(blank=True, choices=[('upload', 'ID Upload'), ('camera', 'Live Camera'), ('manual', 'Manual Verification')], max_length=20, null=True, verbose_name='Verification Method')),
                ('id_verification_date', models.DateTimeField(blank=True, null=True)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='loan_verifications/', verbose_name='ID Document')),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('arrears_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('days_in_arrears', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('pending_verification', 'Pending ID Verification'), ('approved', 'Approved'), ('disbursed', 'Disbursed'), ('active', 'Active'), ('completed', 'Completed'), ('defaulted', 'Defaulted'), ('rejected', 'Rejected')], default='draft', max_length=25)),
                ('is_active', models.BooleanField(default=True)),
                ('top_up_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Top-up Amount')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
                ('original_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='top_up_loans', to='loans.loan')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan',
                'verbose_name_plural': 'Loans',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='LoanTopUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_up_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('reason', models.TextField(verbose_name='Top-up Reason')),
                ('approval_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('requires_new_verification', models.BooleanField(default=False)),
                ('previous_repayment_performance', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Repayment Performance %')),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_top_ups', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_ups', to='loans.loan')),
                ('top_up_loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='top_up_request', to='loans.loan')),
            ],
            options={
                'verbose_name': 'Loan Top-Up',
                'verbose_name_plural': 'Loan Top-Ups',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IDVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_method', models.CharField(choices=[('upload', 'ID Document Upload'), ('camera', 'Live Camera Capture'), ('manual', 'Manual Verification')], max_length=20)),
                ('id_number', models.CharField(max_length=20, verbose_name='ID Number')),
                ('id_type', models.CharField(choices=[('national_id', 'National ID'), ('passport', 'Passport'), ('driving_license', 'Driving License')], default='national_id', max_length=20)),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='id_verifications/front/')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='id_verifications/back/')),
                ('live_photo', models.ImageField(blank=True, null=True, upload_to='id_verifications/live/')),
                ('verification_data', models.JSONField(blank=True, null=True)),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Confidence Score')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_verification', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='id_verifications', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ID Verification',
                'verbose_name_plural': 'ID Verifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LoanRepayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repayment_date', models.DateField()),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('principal_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('interest_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('adjustment', 'Adjustment')], default='cash', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('arrears_cleared', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('penalty_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_verified', models.BooleanField(default=False)),
                ('verification_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_loanrepayments', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repayments', to='loans.loan')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Repayment',
                'verbose_name_plural': 'Loan Repayments',
                'ordering': ['-repayment_date', '-created_at'],
                'indexes': [models.Index(fields=['loan', 'repayment_date'], name='loans_loanr_loan_id_e9e725_idx'), models.Index(fields=['receipt_number'], name='loans_loanr_receipt_40f1a1_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['loan_type', 'status'], name='loans_loan_loan_ty_3934a2_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['group', 'member'], name='loans_loan_group_i_f6f071_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['due_date'], name='loans_loan_due_dat_1042a5_idx'),
        ),
        migrations.AddIndex(
            model_name='loan',
            index=models.Index(fields=['id_verified'], name='loans_loan_id_veri_e86dcc_idx'),
        ),
    ]
