# Generated by Django 4.2.26 on 2025-11-07 09:45

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0002_group_contact_email_group_contact_person_and_more'),
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_date', models.DateTimeField(auto_now_add=True)),
                ('submitted_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('under_review', 'Under Review'), ('pending_guarantors', 'Pending Guarantor Approval'), ('pending_verification', 'Pending ID Verification'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='draft', max_length=25)),
                ('business_plan', models.FileField(blank=True, null=True, upload_to='business_plans/')),
                ('project_description', models.TextField(blank=True, null=True)),
                ('expected_returns', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('required_guarantors', models.PositiveIntegerField(default=1, verbose_name='Required Guarantors')),
                ('min_guarantee_percentage', models.DecimalField(decimal_places=2, default=20, max_digits=5, verbose_name='Minimum Guarantee Coverage %')),
                ('reviewed_date', models.DateTimeField(blank=True, null=True)),
                ('review_notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_applications', to='groups.group')),
                ('loan', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='loans.loan')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_applications', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Loan Application',
                'verbose_name_plural': 'Loan Applications',
                'ordering': ['-application_date'],
            },
        ),
        migrations.CreateModel(
            name='Guarantor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('guarantee_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='Guarantee Amount')),
                ('guarantee_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Guarantee Percentage')),
                ('status', models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='pending', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('group_member', 'Group Member'), ('family', 'Family Member'), ('friend', 'Friend'), ('business_partner', 'Business Partner'), ('other', 'Other')], default='group_member', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_guarantors', to=settings.AUTH_USER_MODEL)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guarantors', to='loans.loan')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guaranteed_loans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantor',
                'verbose_name_plural': 'Guarantors',
                'ordering': ['-created_at'],
                'unique_together': {('loan', 'member')},
            },
        ),
    ]
