# Generated by Django 4.2.26 on 2025-11-07 11:13

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loans', '0002_loanapplication_guarantor'),
        ('groups', '0003_cashintransaction_related_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('id_number', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='ID number must be 6-8 digits', regex='^[0-9]{6,8}$')])),
                ('phone_number', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: +254712345678', regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('marital_status', models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=10, null=True)),
                ('education_level', models.CharField(blank=True, choices=[('primary', 'Primary School'), ('secondary', 'Secondary School'), ('diploma', 'Diploma'), ('degree', 'Bachelor Degree'), ('masters', 'Masters'), ('phd', 'PhD'), ('other', 'Other')], max_length=20, null=True)),
                ('occupation', models.CharField(max_length=100)),
                ('employer', models.CharField(blank=True, max_length=100, null=True)),
                ('monthly_income', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('county', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('date_joined', models.DateField(default=datetime.date.today)),
                ('membership_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('terminated', 'Terminated')], default='active', max_length=20)),
                ('membership_type', models.CharField(choices=[('regular', 'Regular Member'), ('premium', 'Premium Member'), ('founder', 'Founder Member')], default='regular', max_length=20)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='member_ids/')),
                ('id_verified', models.BooleanField(default=False)),
                ('id_verification_date', models.DateTimeField(blank=True, null=True)),
                ('live_photo', models.ImageField(blank=True, null=True, upload_to='member_photos/')),
                ('biometric_data', models.BinaryField(blank=True, null=True)),
                ('biometric_verified', models.BooleanField(default=False)),
                ('total_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loans_taken', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_loans_repaid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_interest_paid', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_welfare_contributions', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_fines_charges', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_month_savings', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_month_welfare', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_month_fines', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('credit_score', models.DecimalField(decimal_places=2, default=50.0, max_digits=5)),
                ('risk_category', models.CharField(choices=[('low', 'Low Risk'), ('medium', 'Medium Risk'), ('high', 'High Risk'), ('very_high', 'Very High Risk')], default='medium', max_length=20)),
                ('savings_consistency', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('loan_repayment_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('member_since_months', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_activity', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_members', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member',
                'verbose_name_plural': 'Members',
                'ordering': ['-date_joined', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='MemberSavings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('savings_type', models.CharField(choices=[('regular', 'Regular Savings'), ('welfare', 'Welfare Contribution'), ('emergency', 'Emergency Fund'), ('investment', 'Investment Savings'), ('fine', 'Fine Payment'), ('other', 'Other')], default='regular', max_length=20)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank', 'Bank Transfer'), ('check', 'Check'), ('adjustment', 'Adjustment')], default='cash', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_savings', to=settings.AUTH_USER_MODEL)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to='members.member')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Savings Transaction',
                'verbose_name_plural': 'Member Savings Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MemberDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('id_card', 'National ID Card'), ('passport', 'Passport'), ('kra_pin', 'KRA PIN Certificate'), ('passport_photo', 'Passport Photo'), ('proof_of_income', 'Proof of Income'), ('bank_statement', 'Bank Statement'), ('utility_bill', 'Utility Bill'), ('other', 'Other Document')], max_length=20)),
                ('document_name', models.CharField(max_length=100)),
                ('document_file', models.FileField(upload_to='member_documents/')),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='members.member')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Member Document',
                'verbose_name_plural': 'Member Documents',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.CreateModel(
            name='MemberActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('savings_deposit', 'Savings Deposit'), ('loan_application', 'Loan Application'), ('loan_repayment', 'Loan Repayment'), ('profile_update', 'Profile Update'), ('document_upload', 'Document Upload'), ('meeting_attendance', 'Meeting Attendance'), ('status_change', 'Status Change'), ('other', 'Other Activity')], max_length=20)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='members.member')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('related_savings', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.membersavings')),
            ],
            options={
                'verbose_name': 'Member Activity',
                'verbose_name_plural': 'Member Activities',
                'ordering': ['-activity_date'],
            },
        ),
        migrations.CreateModel(
            name='CreditScoreHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_date', models.DateField(default=datetime.date.today)),
                ('credit_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('risk_category', models.CharField(max_length=20)),
                ('savings_consistency', models.DecimalField(decimal_places=2, max_digits=5)),
                ('loan_repayment_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('membership_duration_months', models.PositiveIntegerField()),
                ('total_fines', models.DecimalField(decimal_places=2, max_digits=12)),
                ('score_change', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('change_reason', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_score_history', to='members.member')),
            ],
            options={
                'verbose_name': 'Credit Score History',
                'verbose_name_plural': 'Credit Score History',
                'ordering': ['-score_date'],
            },
        ),
        migrations.CreateModel(
            name='NextOfKin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('parent', 'Parent'), ('child', 'Child'), ('sibling', 'Sibling'), ('relative', 'Relative'), ('friend', 'Friend'), ('other', 'Other')], max_length=20)),
                ('id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_primary_contact', models.BooleanField(default=False)),
                ('contact_priority', models.PositiveIntegerField(default=1)),
                ('id_document', models.FileField(blank=True, null=True, upload_to='next_of_kin_ids/')),
                ('verified', models.BooleanField(default=False)),
                ('occupation', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_of_kin', to='members.member')),
            ],
            options={
                'verbose_name': 'Next of Kin',
                'verbose_name_plural': 'Next of Kin',
                'ordering': ['contact_priority', 'full_name'],
                'unique_together': {('member', 'phone_number')},
            },
        ),
        migrations.AddIndex(
            model_name='membersavings',
            index=models.Index(fields=['member', 'transaction_date'], name='members_mem_member__3ac1e9_idx'),
        ),
        migrations.AddIndex(
            model_name='membersavings',
            index=models.Index(fields=['savings_type'], name='members_mem_savings_7dfad9_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['member', 'activity_date'], name='members_mem_member__64daa1_idx'),
        ),
        migrations.AddIndex(
            model_name='memberactivity',
            index=models.Index(fields=['activity_type'], name='members_mem_activit_eb61f5_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['member_number'], name='members_mem_member__425bc1_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['id_number'], name='members_mem_id_numb_c622c7_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['phone_number'], name='members_mem_phone_n_28ee55_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['group', 'membership_status'], name='members_mem_group_i_fa482b_idx'),
        ),
        migrations.AddIndex(
            model_name='member',
            index=models.Index(fields=['credit_score'], name='members_mem_credit__e9525e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='creditscorehistory',
            unique_together={('member', 'score_date')},
        ),
    ]
