# Generated by Django 4.2.26 on 2025-11-10 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_event_eventattendance_event_attendees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officeralert',
            name='alert_type',
            field=models.CharField(choices=[('meeting_reminder', 'Meeting Reminder'), ('visit_reminder', 'Field Visit Reminder'), ('event_reminder', 'Event Reminder'), ('loan_overdue', 'Loan Overdue Alert'), ('savings_target', 'Savings Target Alert'), ('performance', 'Performance Alert'), ('system', 'System Alert'), ('other', 'Other Alert')], max_length=20),
        ),
    ]
