# Generated by Django 4.2.26 on 2025-11-10 17:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0003_alter_officeralert_alert_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('view', 'View'), ('login', 'Login'), ('logout', 'Logout'), ('export', 'Export'), ('import', 'Import'), ('approve', 'Approve'), ('reject', 'Reject'), ('bulk_update', 'Bulk Update'), ('other', 'Other')], max_length=20)),
                ('target_type', models.CharField(help_text='Model name of the target object', max_length=50)),
                ('target_id', models.PositiveIntegerField(help_text='ID of the target object')),
                ('old_value', models.JSONField(blank=True, help_text='Previous state as JSON', null=True)),
                ('new_value', models.JSONField(blank=True, help_text='New state as JSON', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(blank=True, help_text='GPS coordinates (lat,long) if available', max_length=100, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, help_text='Human-readable description', null=True)),
                ('session_id', models.CharField(blank=True, max_length=100, null=True)),
                ('request_id', models.CharField(blank=True, max_length=100, null=True)),
                ('actor', models.ForeignKey(help_text='User who performed the action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp'], name='dashboard_a_timesta_3a0d49_idx'), models.Index(fields=['actor', 'timestamp'], name='dashboard_a_actor_i_4d49db_idx'), models.Index(fields=['action_type', 'timestamp'], name='dashboard_a_action__28eced_idx'), models.Index(fields=['target_type', 'target_id'], name='dashboard_a_target__8debb7_idx')],
            },
        ),
    ]
