# Generated by Django 4.2.7 on 2025-11-10 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('groups', '0003_cashintransaction_related_loan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_type', models.CharField(choices=[('saving', 'Saving'), ('welfare', 'Welfare'), ('fine', 'Fine'), ('appreciation_fee', 'Appreciation Fee'), ('application_fee', 'Application Fee'), ('project_contribution', 'Project Contribution')], max_length=30)),
                ('reference', models.CharField(blank=True, max_length=255, null=True)),
                ('transaction_date', models.DateField(default=django.utils.timezone.now)),
                ('balance_after', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions', to='groups.group')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_transactions_new', to='members.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date'],
            },
        ),
    ]
