# Generated by Django 4.2.7 on 2025-11-10 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('savings', '0001_initial'),
    ]

    operations = [
    ]
