# Generated by Django 4.2.26 on 2025-11-07 11:45

import datetime
from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('loans', '0002_loanapplication_guarantor'),
        ('members', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_cashintransaction_related_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category_type', models.CharField(choices=[('income', 'Income Category'), ('expense', 'Expense Category')], max_length=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('has_budget', models.BooleanField(default=False)),
                ('monthly_budget', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'verbose_name': 'Transaction Category',
                'verbose_name_plural': 'Transaction Categories',
                'ordering': ['category_type', 'name'],
                'unique_together': {('name', 'category_type')},
            },
        ),
        migrations.CreateModel(
            name='TransactionReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciliation_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('reconciliation_date', models.DateField(default=datetime.date.today)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_in', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cash_out', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('expected_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('actual_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('variance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('disputed', 'Disputed')], default='pending', max_length=20)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('variance_explanation', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_completed_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions_created_reconciliations', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_reconciliations', to='groups.group')),
            ],
            options={
                'verbose_name': 'Transaction Reconciliation',
                'verbose_name_plural': 'Transaction Reconciliations',
                'ordering': ['-reconciliation_date'],
                'unique_together': {('group', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='CashOutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('loan_disbursement', 'Loan Disbursement'), ('member_withdrawal', 'Member Savings Withdrawal'), ('operational_expense', 'Operational Expense'), ('welfare_payout', 'Welfare Payout'), ('supplier_payment', 'Supplier Payment'), ('staff_salary', 'Staff Salary'), ('utility_bill', 'Utility Bill'), ('other_expense', 'Other Expense')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking'), ('other', 'Other')], default='cash', max_length=20)),
                ('payee_name', models.CharField(max_length=200)),
                ('payee_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('payee_id_number', models.CharField(blank=True, max_length=20, null=True)),
                ('cheque_number', models.CharField(blank=True, max_length=50, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=50, null=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='M-Pesa Code')),
                ('description', models.TextField()),
                ('purpose', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending_approval', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('requested_date', models.DateTimeField(auto_now_add=True)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('approval_notes', models.TextField(blank=True, null=True)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='cash_out_documents/', verbose_name='Supporting Document')),
                ('receipt_document', models.FileField(blank=True, null=True, upload_to='cash_out_receipts/', verbose_name='Receipt Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_out_transactions', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_cash_out_transactions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cash_out_transactions', to='groups.group')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_out_transactions', to='loans.loan')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_out_transactions', to='members.member')),
                ('paid_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='paid_cash_out_transactions', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_cash_out_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash Out Transaction',
                'verbose_name_plural': 'Cash Out Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='transaction_transac_506311_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_208975_idx'), models.Index(fields=['status'], name='transaction_status_699cad_idx'), models.Index(fields=['group', 'transaction_date'], name='transaction_group_i_266a92_idx'), models.Index(fields=['member', 'transaction_date'], name='transaction_member__f3f11c_idx')],
            },
        ),
        migrations.CreateModel(
            name='CashInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('transaction_type', models.CharField(choices=[('savings', 'Member Savings'), ('loan_repayment', 'Loan Repayment'), ('welfare', 'Welfare Contribution'), ('fine', 'Fine Payment'), ('membership_fee', 'Membership Fee'), ('donation', 'Donation'), ('investment', 'Investment Income'), ('other_income', 'Other Income')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('mpesa', 'M-Pesa'), ('bank_transfer', 'Bank Transfer'), ('cheque', 'Cheque'), ('mobile_banking', 'Mobile Banking'), ('other', 'Other')], default='cash', max_length=20)),
                ('receipt_number', models.CharField(blank=True, max_length=100, null=True)),
                ('transaction_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_code', models.CharField(blank=True, max_length=20, null=True, verbose_name='M-Pesa Code')),
                ('description', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_date', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='cash_in_documents/', verbose_name='Supporting Document')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions_cash_in_transactions', to='groups.group')),
                ('loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_in_transactions', to='loans.loan')),
                ('member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_in_transactions', to='members.member')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_cash_in_transactions', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_cash_in_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cash In Transaction',
                'verbose_name_plural': 'Cash In Transactions',
                'ordering': ['-transaction_date', '-created_at'],
                'indexes': [models.Index(fields=['transaction_date'], name='transaction_transac_507e3b_idx'), models.Index(fields=['transaction_type'], name='transaction_transac_32f5f3_idx'), models.Index(fields=['status'], name='transaction_status_8f52e3_idx'), models.Index(fields=['group', 'transaction_date'], name='transaction_group_i_105404_idx'), models.Index(fields=['member', 'transaction_date'], name='transaction_member__53fcea_idx')],
            },
        ),
    ]
