# Generated by Django 4.2.26 on 2025-11-07 15:09

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0001_initial'),
        ('dividends', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DividendDistribution',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('distribution_date', models.DateField()),
                ('total_distributed', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dividend Distribution',
                'verbose_name_plural': 'Dividend Distributions',
                'ordering': ['-distribution_date'],
            },
        ),
        migrations.CreateModel(
            name='DividendPeriod',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('period_type', models.CharField(choices=[('annual', 'Annual')], default='annual', max_length=20)),
                ('year', models.PositiveIntegerField(unique=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('calculation_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('calculated', 'Calculated'), ('approved', 'Approved'), ('distributed', 'Distributed')], default='draft', max_length=20)),
                ('visible_to_field_officers', models.BooleanField(default=False)),
                ('visible_to_members', models.BooleanField(default=False)),
                ('total_income', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_expenses', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('net_profit', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserve_percentage', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('development_percentage', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('dividend_percentage', models.DecimalField(decimal_places=2, default=70.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserve_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('development_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_dividend_pool', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
            ],
            options={
                'verbose_name': 'Dividend Period',
                'verbose_name_plural': 'Dividend Periods',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='MemberDividend',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('savings_based_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('patronage_based_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_dividend', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('calculation_method', models.CharField(default='hybrid_60_40', max_length=50)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('distributed', models.BooleanField(default=False)),
                ('distribution_date', models.DateField(blank=True, null=True)),
                ('distribution_method', models.CharField(blank=True, choices=[('cash', 'Cash'), ('savings_account', 'Savings Account'), ('reinvestment', 'Reinvestment')], max_length=50)),
                ('dividend_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividends.dividendperiod')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.member')),
            ],
            options={
                'verbose_name': 'Member Dividend',
                'verbose_name_plural': 'Member Dividends',
                'ordering': ['-dividend_period__year', 'member__first_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='dividendperiod',
            constraint=models.UniqueConstraint(fields=('year',), name='unique_dividend_year'),
        ),
        migrations.AddField(
            model_name='dividenddistribution',
            name='distributed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dividenddistribution',
            name='dividend_period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dividends.dividendperiod'),
        ),
        migrations.AlterUniqueTogether(
            name='memberdividend',
            unique_together={('dividend_period', 'member')},
        ),
    ]
