# Generated by Django 4.2.26 on 2025-11-10 16:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dashboard', '0001_initial'),
        ('loans', '0002_loanapplication_guarantor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0003_cashintransaction_related_loan'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_type', models.CharField(choices=[('africastalking', "Africa's Talking"), ('twilio', 'Twilio'), ('custom', 'Custom Provider')], max_length=20)),
                ('api_key', models.CharField(max_length=200)),
                ('api_secret', models.CharField(blank=True, max_length=200, null=True)),
                ('sender_id', models.CharField(help_text='Sender ID for SMS', max_length=20)),
                ('base_url', models.URLField(blank=True, null=True)),
                ('rate_per_sms', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('is_active', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMS Provider',
                'verbose_name_plural': 'SMS Providers',
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('template_type', models.CharField(choices=[('loan_balance', 'Loan Balance Update'), ('meeting_notification', 'Meeting Notification'), ('savings_update', 'Savings Update'), ('welcome', 'Welcome Message'), ('reminder', 'Reminder')], max_length=20)),
                ('subject_template', models.CharField(blank=True, max_length=200, null=True)),
                ('message_template', models.TextField()),
                ('available_variables', models.JSONField(blank=True, help_text='JSON list of available variables for this template', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message Template',
                'verbose_name_plural': 'Message Templates',
                'ordering': ['template_type', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(default=uuid.uuid4, max_length=50, unique=True)),
                ('message_type', models.CharField(choices=[('loan_balance', 'Loan Balance Update'), ('meeting_notification', 'Meeting Notification'), ('savings_update', 'Savings Update'), ('general', 'General Message')], max_length=20)),
                ('delivery_method', models.CharField(choices=[('sms', 'SMS'), ('email', 'Email'), ('both', 'SMS and Email')], default='sms', max_length=10)),
                ('recipient_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('recipient_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message_body', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('failed', 'Failed'), ('delivered', 'Delivered')], default='pending', max_length=20)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('failed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('retry_count', models.PositiveIntegerField(default=0)),
                ('provider_reference', models.CharField(blank=True, max_length=100, null=True)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('related_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('related_loan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='loans.loan')),
                ('related_meeting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.meetingschedule')),
                ('sent_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['recipient', 'status'], name='messaging_m_recipie_b42201_idx'), models.Index(fields=['message_type', 'status'], name='messaging_m_message_745440_idx'), models.Index(fields=['sent_at'], name='messaging_m_sent_at_2aa227_idx')],
            },
        ),
    ]
