# Generated by Django 4.2.26 on 2025-11-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='related_field_visit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dashboard.fieldvisit'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('loan_balance', 'Loan Balance Update'), ('meeting_notification', 'Meeting Notification'), ('meeting_reminder', 'Meeting Reminder'), ('visit_reminder', 'Field Visit Reminder'), ('savings_update', 'Savings Update'), ('general', 'General Message')], max_length=20),
        ),
    ]
