# Generated by Django 4.2.26 on 2025-11-10 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_related_field_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_at',
            field=models.DateTimeField(blank=True, help_text='Timestamp when record was soft deleted', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='Soft delete flag for sync purposes'),
        ),
        migrations.AddField(
            model_name='message',
            name='last_sync_at',
            field=models.DateTimeField(blank=True, help_text='Last time this record was synchronized', null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='sync_token',
            field=models.CharField(blank=True, help_text='Unique token for sync conflict resolution', max_length=100, null=True, unique=True),
        ),
    ]
