# Generated by Django 4.2.26 on 2025-11-07 07:50

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('registration_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('county', models.CharField(max_length=100)),
                ('constituency', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('village', models.CharField(max_length=100)),
                ('chairperson_name', models.CharField(max_length=255)),
                ('chairperson_phone', models.CharField(max_length=15)),
                ('chairperson_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('secretary_name', models.CharField(blank=True, max_length=255, null=True)),
                ('treasurer_name', models.CharField(blank=True, max_length=255, null=True)),
                ('formation_date', models.DateField()),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('total_members', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20)),
                ('initial_capital', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL)),
                ('field_officer', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'field_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Group',
                'verbose_name_plural': 'Groups',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='GroupMeeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateTimeField()),
                ('venue', models.CharField(max_length=255)),
                ('agenda', models.TextField(blank=True, null=True)),
                ('minutes', models.TextField(blank=True, null=True)),
                ('total_attendance', models.PositiveIntegerField(default=0)),
                ('decisions_made', models.TextField(blank=True, null=True)),
                ('amount_collected', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='groups.group')),
            ],
            options={
                'verbose_name': 'Group Meeting',
                'verbose_name_plural': 'Group Meetings',
                'ordering': ['-meeting_date'],
            },
        ),
        migrations.CreateModel(
            name='MeetingAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended', models.BooleanField(default=True)),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('contribution_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('comments', models.TextField(blank=True, null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='groups.groupmeeting')),
            ],
            options={
                'verbose_name': 'Meeting Attendance',
                'verbose_name_plural': 'Meeting Attendances',
            },
        ),
        migrations.CreateModel(
            name='CashOutTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('service_fee', 'Service Fee'), ('welfare', 'Welfare Payment'), ('loan_to_ukombozini', 'Loan to Ukombozini'), ('short_term_loans', 'Short Term Loans Disbursement'), ('long_term_loans', 'Long Term Loans Disbursement'), ('operational_costs', 'Operational Costs'), ('dividends', 'Dividends Payment'), ('other', 'Other Expenses')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField()),
                ('transaction_date', models.DateField()),
                ('voucher_number', models.CharField(blank=True, max_length=50, null=True)),
                ('recipient_name', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_out_transactions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Cash Out Transaction',
                'verbose_name_plural': 'Cash Out Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CashInTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('banking', 'Banking'), ('short_term_loans', 'Short Term Loans'), ('long_term_loans', 'Long Term Loans'), ('savings', 'Savings'), ('welfare', 'Welfare'), ('education_project', 'Education Project'), ('agriculture_project', 'Agriculture Project'), ('ukombozini_loan', 'Ukombozini Loan'), ('application_fee', 'Application Fee'), ('appreciation_fee', 'Appreciation Fee')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField()),
                ('receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_in_transactions', to='groups.group')),
            ],
            options={
                'verbose_name': 'Cash In Transaction',
                'verbose_name_plural': 'Cash In Transactions',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TRFBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance_date', models.DateField()),
                ('balance_account', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('short_term_arrears', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('long_term_loans_balance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_assets', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_liabilities', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('net_worth', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trf_balances', to='groups.group')),
            ],
            options={
                'verbose_name': 'TRF Balance',
                'verbose_name_plural': 'TRF Balances',
                'ordering': ['-balance_date'],
                'unique_together': {('group', 'balance_date')},
            },
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['county', 'constituency'], name='groups_grou_county_6a2032_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['status'], name='groups_grou_status_952d41_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['registration_date'], name='groups_grou_registr_32dd91_idx'),
        ),
        migrations.AddIndex(
            model_name='cashouttransaction',
            index=models.Index(fields=['group', 'transaction_date'], name='groups_cash_group_i_55056f_idx'),
        ),
        migrations.AddIndex(
            model_name='cashouttransaction',
            index=models.Index(fields=['transaction_type'], name='groups_cash_transac_89b578_idx'),
        ),
        migrations.AddIndex(
            model_name='cashintransaction',
            index=models.Index(fields=['group', 'transaction_date'], name='groups_cash_group_i_b5102c_idx'),
        ),
        migrations.AddIndex(
            model_name='cashintransaction',
            index=models.Index(fields=['transaction_type'], name='groups_cash_transac_3a2625_idx'),
        ),
    ]
