# Generated by Django 4.2.26 on 2025-11-07 08:11

from decimal import Decimal
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Contact Email'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_person',
            field=models.CharField(default='Chairperson', max_length=255, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='group',
            name='contact_phone',
            field=models.CharField(default='+254700000000', max_length=15, verbose_name='Contact Phone'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='group',
            name='chairperson_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Chairperson Email'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chairperson_name',
            field=models.CharField(max_length=255, verbose_name='Chairperson Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='chairperson_phone',
            field=models.CharField(max_length=15, verbose_name='Chairperson Phone'),
        ),
        migrations.AlterField(
            model_name='group',
            name='constituency',
            field=models.CharField(max_length=100, verbose_name='Constituency'),
        ),
        migrations.AlterField(
            model_name='group',
            name='county',
            field=models.CharField(max_length=100, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='group',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_groups', to=settings.AUTH_USER_MODEL, verbose_name='Created By'),
        ),
        migrations.AlterField(
            model_name='group',
            name='current_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Current Balance'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Group Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='field_officer',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'field_officer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_groups', to=settings.AUTH_USER_MODEL, verbose_name='Field Officer'),
        ),
        migrations.AlterField(
            model_name='group',
            name='formation_date',
            field=models.DateField(verbose_name='Formation Date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='initial_capital',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Initial Capital'),
        ),
        migrations.AlterField(
            model_name='group',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='registration_date',
            field=models.DateField(auto_now_add=True, verbose_name='Registration Date'),
        ),
        migrations.AlterField(
            model_name='group',
            name='registration_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='Registration Number'),
        ),
        migrations.AlterField(
            model_name='group',
            name='secretary_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Secretary Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended'), ('closed', 'Closed')], default='active', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='group',
            name='total_members',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Members'),
        ),
        migrations.AlterField(
            model_name='group',
            name='treasurer_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Treasurer Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='village',
            field=models.CharField(max_length=100, verbose_name='Village'),
        ),
        migrations.AlterField(
            model_name='group',
            name='ward',
            field=models.CharField(max_length=100, verbose_name='Ward'),
        ),
    ]
