# Generated by Django 4.2.26 on 2025-11-07 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loanapplication_guarantor'),
        ('groups', '0002_group_contact_email_group_contact_person_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cashintransaction',
            name='related_loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appreciation_fees', to='loans.loan'),
        ),
    ]
